pruebaprueba:
    resource: "@PruebapruebaBundle/Controller/"
    type:     annotation
    prefix:   /

acme_prueba:
    resource: "@AcmePruebaBundle/Controller/"
    type:     annotation
    prefix:   /

